### ISSUE TITLE
[RELEASE CHECKLIST] GCPy 1.0.0

### ISSUE THREAD

**Issue by WilliamDowns** [geoschem/gcpy#89]
# Checklist for releasing GCPy 1.0.0

## Test scripts

All of the benchmark scripts must complete with no errors and with verified correct results for GEOS-Chem 13.0.0 for both GEOS-Chem Classic and GCHP.

- [x] run_1mo_benchmark.py
- [x] run_1yr_fullchem_benchmark.py
- [x] run_1yr_tt_benchmark.py

## Software releases
- [x] Publish new release on Github
- [x] Add DOI
- [x] Publish release to PyPi
- [x] Publish release to conda-forge
- [x] Add documentation for procuring source code when installing through conda / pip

## Data
- [x] Update test data on gcgrid for GEOS-Chem 13.0.0

## Documentation
- [x] Create a ReadTheDocs site for GCPy 1.0.0
- [x] Link to ReadTheDocs on the GEOS-Chem Wiki
- [x] Create and release a tutorial video, "Getting started with GCPy 1.0.0"

## Announcement
- [x] Send email to user list announcing release

**Comment by yantosca** [comment]
GCPy 1.0.0 is now officially released.  We will close this out.
